[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor_metadata = false

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[doc]
out = "docs"
title = "Address Entropy"

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
sepolia = "https://rpc.ankr.com/eth_sepolia"
shape = "https://mainnet.shape.network"
